### ISSUE TITLE
trying the LFQ-Analyst on my desktop

### ISSUE THREAD

**Issue by fazeliniah** [MonashBioinformaticsPlatform/LFQ-Analyst#1]
Thank you for developing this exciting new tool.  I have downloaded the source for github and am trying to run the shinny app on my local machine. I tested the demo data. It seems to be running and it generating the figures. However, it produces the error for the "LFQ Results Table" (Please see the attached file). Any idea why this is happening? I am using the updated RStudio (version 1.2.5001). 
![Screen Shot 2019-10-30 at 3 55 17 PM](https://user-images.githubusercontent.com/19155957/67896229-5127a500-fb32-11e9-9205-0c8e2662b8b3.png)

**Comment by anupshah14** [comment]
Would you like to comment on the version of R and dplyr at your end. I suspect the error is most likely due to newer versions on either of those. The live version is hosted on `R 3.4.3`.

**Comment by fazeliniah** [comment]
R version is 3.6.1 and dplyr is 0.8.3. Should I use the R 3.4.3 instead?

**Comment by anupshah14** [comment]
You could try older version of dplyr as well. ex. `dplyr_0.7.4`

**Comment by fazeliniah** [comment]
Thank you for your advice. I didn't have much luck with the older versions of R and dplyr. Any chance that you update the software in the future?  In the meantime I use the version hosted on your website. Thanks again for developing this tool.

**Comment by anupshah14** [comment]
Thanks for your interest and feedback.
I have now created the **dev branch** and pushed updates for `R 3.6.0`. Also included the `dependency.txt` file in each branch which reflects `sessionInfo()` of R environment. I have tested on my end. Let me know how you go.

**Comment by fazeliniah** [comment]
Works beautifully now. Thanks again!

**Comment by fazeliniah** [comment]
The last problem seems to be with the Erichment (please see the attached screen shot). I am working with the demo data and here is the error: "Please run `test_gsea()` with valid databases as argument". It is from the DEP package. 
![Screen Shot 2019-11-01 at 12 54 42 PM](https://user-images.githubusercontent.com/19155957/68042113-7807e780-fca8-11e9-9ce2-15139d3afab4.png)

**Comment by anupshah14** [comment]
Hi, 
I could not reproduce the error about the enrichment analysis at my end. 
What were the warnings in console?

**Comment by fazeliniah** [comment]
Hello, 
The error is :
"Error: Please run `test_gsea()` with valid databases as argument
See http://amp.pharm.mssm.edu/Enrichr/ for available databases". 
Do I need to download the Gene Ontology/Pathway databases from Enrichr site?
Thanks

**Comment by anupshah14** [comment]
You don't need to download the databases, as LFQ-analyst makes API calls to EnrichR. I just pushed some changes to dev branch that might solve the issue at your end.

**Comment by fazeliniah** [comment]
I tested the new changes and it seems the problem is with the website. Any advice?
Here is the message I got:

Uploading data to Enrichr... Done.
  Querying GO_Molecular_Function_2017b... Done.
Parsing results... Done.
EnrichR website not responding
Warning: Error in test_gsea: Please run `test_gsea()` with valid databases as argument
See http://amp.pharm.mssm.edu/Enrichr/ for available databases

**Comment by fazeliniah** [comment]
To make sure I have connection, I also tested the EnrichR website and it is working just fine.

**Comment by anupshah14** [comment]
Try now with this commit https://github.com/MonashBioinformaticsPlatform/LFQ-Analyst/commit/e1197f513b47ab35c2c617b0b0628a7a3a9bb1d1

**Comment by fazeliniah** [comment]
Perfect. It is now working! Thanks again for all your help and quick fixes.
