### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Joaquin-c4** [MonashBioinformaticsPlatform/LFQ-Analyst#13]
hello, im having this error with the online platform when i run the analyis: specified 'columns' should be numeric
         Run make_se_parse() with the appropriate columns as argument

i add the "gene name" and "protein name" colums to my proteinGroup file because i only had the protein ID in te origilan file... i belive it could be a problems with these columns

[protein_group_annotations.txt](https://github.com/MonashBioinformaticsPlatform/LFQ-Analyst/files/9385701/protein_group_annotations.txt)
[exp_disign_.txt](https://github.com/MonashBioinformaticsPlatform/LFQ-Analyst/files/9385706/exp_disign_.txt)

**Comment by Hailey-Z** [comment]
Hi, @Joaquin-c4 thanks for your feedback,  the abundance columns in this dataset are not in numeric format, we’ve fixed it by converting these columns to the correct format. One more thing is that the label columns in the exp_design file cannot start with a number, as the inside code will prefix the label with “X”, please use the following modified exp_design file to run your analysis, thank you.
[exp_design_modified.txt](https://github.com/MonashBioinformaticsPlatform/LFQ-Analyst/files/9424069/exp_design_modified.txt)
