### ISSUE TITLE
Docker installation not successful

### ISSUE THREAD

**Issue by HYTang69** [MonashBioinformaticsPlatform/LFQ-Analyst#16]
Hi,
I tried to install this using Docker, but was not successful.

On Chrome browser:
http://localhost:3838/lfq-analyst/
An error has occurred!
An error has occurred. Check your logs or contact the app author for clarification.

On my command prompt:
Listening on http://127.0.0.1:42867
Warning: Good news!
You don't need to call `useShinyalert()` anymore. Please remove this line from your code.
If you really want to pre-load {shinyalert} to the UI for any reason, use:
        `useShinyalert(force = TRUE)`
The `name` provided ('home') is deprecated in Font Awesome 6:
* please consider using 'house' or 'fas fa-house' instead
* use the `verify_fa = FALSE` to deactivate these messages
Warning: Error in : 'imputeMethods' is not an exported object from 'namespace:MSnbase'
  83: normalizeChoicesArgs
  82: radioButtons
  69: ui [/srv/shiny-server/lfq-analyst/ui.R#2]
   1: runApp

Any idea?

Thanks for looking into this.
Hsin-Yao

**Comment by Hailey-Z** [comment]
Hi, @HYTang69 thanks for your feedback, the one in the master branch is based on R3.4.2, you can switch to the dev_for_R4.2.1 7627958064045bd43cdf6ac4f6757c4a2b2fc9ed, to either use Docker or run it locally. Thanks very much.

**Comment by HYTang69** [comment]
Thanks! That works. FYI, shinycssloaders is missing in Dockerfile.

**Comment by Hailey-Z** [comment]
That's great, thanks @HYTang69 , I'll update the Dockerfile.
