### ISSUE TITLE
Percentage next to protein in volcano plot

### ISSUE THREAD

**Issue by Klyper** [MonashBioinformaticsPlatform/LFQ-Analyst#23]
Dear Developers. 

When in the dev version of LFQ-Analyst you make a volcano plot and select proteins, percentages appear next to the proteins.
What do these values indicate?
I looked in the manual but could not find any explanation.

Kind regards
Klaas

**Comment by Hailey-Z** [comment]
Hi @Klyper , thanks for your feedback. It shows the percentage of imputed values in a protein. The reliability should be considered if the percentage is high, as most of the intensity values are imputed. Sorry for the confusion, we will improve to make it more understandable.

Cheers.

**Comment by Klyper** [comment]
Thanks for the quick response! 
Cheers
