### ISSUE TITLE
Error : LFQ Results Table

### ISSUE THREAD

**Issue by Hayoung-hiro** [MonashBioinformaticsPlatform/LFQ-Analyst#3]
Hi 

Thank you for your great works.

every thing is doing well except LFQ Results Table when using shiny.

![image](https://user-images.githubusercontent.com/16012339/73608923-cf04bc00-460b-11ea-8c12-0f1dd94463be.png)

Like the image that I uploaded, I got those messages on my rstudio.

"Error in : `df` must be a data frame without row names in `column_to_rownames()`.
  132"

It is really helpful that let you know how to fix this problem.

Thank you.

**Comment by anupshah14** [comment]
The issue seems like with recent version of `R` and `tidyverse` and being fixed in the **dev** branch which you can clone using following command. 

`git clone --single-branch --branch dev https://github.com/MonashBioinformaticsPlatform/LFQ-Analyst.git`

Hope that helps.
